# Generated by Django 4.0.1 on 2022-01-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=32)),
                ('finished', models.BooleanField(db_column='finished', default=False)),
                ('description', models.TextField(db_column='worklog')),
                ('deadline', models.DateField(db_column='deadline')),
            ],
        ),
    ]
